categories:
  CozyBackend: ~
  CozyBackend.defaults.paths:
    parent: CozyBackend
    label: 'Paths'
  CozyBackend.defaults.tt_content:
    parent: CozyBackend
    label: 'TTContent'
  CozyBackend.defaults.pages:
    parent: CozyBackend
    label: 'Pages'

settings:
  componentsPath:
    label: 'Component Path'
    category: CozyBackend.defaults.paths
    description: 'Paths für components'
    type: string
    default: 'Resources/Private/Components/'
  designTokens:
    label: 'Design Token Path'
    category: CozyBackend.defaults.paths
    description: 'Paths für designTokens'
    type: string
    default: 'Tokens/designTokens.json'
  tt_content.default.header:
    label: 'Default Text für Inhaltselemente'
    category: CozyBackend.defaults.tt_content
    description: 'Overrides default text'
    type: string
    default: 'Hier ist ein Headertext'
  tt_content.default.layout:
    category: CozyBackend.defaults.tt_content
    type: string
    default: 2
    enum:
      0: 'Default'
      1: 'Container'
      2: 'Text'
      3: 'Kachel'
  pages.default.abstract:
    label: 'Default Abstract of Page'
    category: CozyBackend.defaults.pages
    type: string
    default: 'Hier kommt ein Abstrakt'