styles:
  templates:
    layoutRootPath: 'EXT:cozy_backend/Resources/Private/Layouts/'
    partialRootPath: 'EXT:cozy_backend/Resources/Private/Partials/'
    templateRootPath: 'EXT:cozy_backend/Resources/Private/Templates/'

page:
  pageview:
    paths: 'EXT:cozy_backend/Resources/Private/PageView/'

  meta:
    viewport: 'width=device-width, initial-scale=1'
    robots: 'index,follow'
    apple-mobile-web-app-capable: 'no'
    compatible: 'IE=edge'

config:
  no_cache: '0'
  removeDefaultJS: '0'
  admPanel: '1'
  prefixLocalAnchors: 'all'
  headerComment: 'build by Nimmermaer'
  sendCacheHeaders: '1'
